config/routes.rb
Rails.application.routes.draw do
  resources :baskets
  resources :products
  root "categories#index"
  resources :categories do 
    resources :products 
  end
  resources :sessions
  resources :users
  get "/signup" => "users#new" 
  resources :users 
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/basket" => "baskets#index"
  post "/basket" => "baskets#create"
  delete "/basket/:id" => "baskets#destroy"

end

app/models/basket.rb
class Basket < ActiveRecord::Base

  has_one :user
  has_many :products
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_one :category
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many  :users
 

end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_and_belongs_to_many :roles

end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  

  #method that check if user is logged in
  def require_user
    redirect_to "/login" unless current_user
  end

  #gets current users role names
  private
  def get_role_array
    role_names = []
    if current_user
      users_roles = UserRole.where(user_id: @current_user.id).to_a 
      users_roles.each do |x|
        role_names << Role.find_by(id: x.role_id).name
      end
    end
    role_names
  end
  
  helper_method :is_admin?
  def is_admin?
    get_role_array.include? "admin"
  end
  helper_method :is_user?
  def is_user?
    get_role_array.include? "user"
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController

  def index

     @baskets = Basket.where(user_id: current_user.id)
     @products = []
     @baskets.each do |b|
       @products <<  Product.find_by_id(b.product_id)
     end
     @products 
  end
  
  def create 
    tmp =  Product.find_by_id(params[:product][:id])
    
    @basket = Basket.create(product_id: params[:product][:id], user_id: current_user.id)
    if tmp.quantity-1 >=0 && tmp.update_attributes(quantity: tmp.quantity-1)
     redirect_to "/"
    end
  end
  
  def destroy
    Basket.find_by_product_id(params[:id]).destroy
    tmp = Product.find_by_id(params[:id])
    tmp.update_attributes(quantity: tmp.quantity + 1)
    redirect_to "/baskets"
  end
 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    tmp = Category.find(params[:category_id] )
    @products = tmp.products
  end

  def show
   @product = Product.find(params[:id])
  end


  def edit
    @product = Product.find(params[:id]) 
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to "/"
    else
      redirect_to edit_product
    end
  end
  

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
      if @product.save
        redirect_to "/"
      else
        redirect_to "/products/new"
      end

  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to "/"
  end


  private
  def product_params
    params.require(:product).permit(:name,:description,:image,:category_id,:quantity,:price)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
   # if @user && @user.authenticate(params[:session][:password])
    #  session[:user_id] = @user.id
   #   redirect_to "/"
   # else
    #  redirect_to "/login" 
   # end
    respond_to do |format|
#   if @user && @user.authenticate(params[:session][:password])
    # format.html{}
     format.js {}
    # format.json {}
  
     

  end 
#      format.html {redirect_to login_path}
     # format.js {render :template => "new.js.erb"}
     # format.html {render :template => "new.html.erb"}
#    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      redirect_to "/signup"
    end
  end 


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/baskets/_form.html.erb
<%= form_for(@basket) do |f| %>
  <% if @basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% @basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing Basket</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Baskets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
 <% if @products %>  
  <% @products.each do |p| %>
<tr>
         <td><%= p.name%></td>
         <td><%= p.price %> </td>
      
      


       <td><%=link_to "Remove from basket", "baskets/"+p.id.to_s, method:"delete"%></td> 
      </tr>
    <% end %>
   <% end %>
  </tbody>
</table>

<br>

app/views/baskets/new.html.erb
<h1>New Basket</h1>

<%= render 'form' %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_basket_path(@basket) %> |
<%= link_to 'Back', baskets_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wellcome to Ruby Shop!</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
       <td><img src=<%=category.image%> height="100" width="50"</td>
        <td><%= link_to category.name, category_products_path(category) %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%if current_user%>
  <ul>
    <li>
      <%= current_user.email%>
    </li>
    <li>
      <%= link_to "Log Out", logout_path, method:"delete" %>
    </li>
  </ul>
<% else %>
   <ul>
     <li>
      <%= link_to "Log In", login_path, method: "get" %>
     </li>

     <li>
       <%= link_to "Sign Up", "signup" %>
     </li>
    </ul>
<%end%>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>


<%= form_for(@product) do |p| %>
<%= label(:product, :category_id)%><br>
<%= collection_select(:product,:category_id, Category.all, :id, :name)%><br> 
<%= label(:product, :name) %><br>
<%= p.text_field :name %><br>
<%= label(:product, :description) %> <br>
<%= p.text_area :description %><br>
<%= label(:product, :image) %><br>
<%= p.text_field :image %><br>
<%= label(:product, :quantity) %><br>
<%= p.number_field :quantity, min: 0 %> <br>
<%= label(:product, :price) %><br>
<%= p.number_field :price, min: 0 %> <br>
<%= p.submit "Edit Product" %>



<%end%>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <tr>
    <% @products.each do |product| %>
      <td>
        <!--
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
     <table>
     <thead></thead> 
     <tbody>
      <tr> 
      <td>
         <img vertical_align="middle" src="<%=product.image %>" width="64" height="380">
      </td>
      </tr>
      <tr>
      <td>
      <%=link_to product.name, product %> 
     </td>
     </tr>
     <tr>
     <td>
     <%= form_for( product, :url => "/basket", :html => { :method => :post } ) do |p| %>
       <%= p.hidden_field :id %>
       <%= p.submit %>
     <% end %>
     </td>
     </tr>     
      </tbody>
     </table></td>
    <% end %>
   </tr>
  </tbody>
</table>

<br>
<%if is_admin?%>
<%= link_to 'New Product', new_product_path %>
<%end%>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_for(@product) do |p| %>
<%= label(:product, :category_id)%><br>
<%= collection_select(:product,:category_id, Category.all, :id, :name)%><br>
<%= label(:product, :name) %><br>
<%= p.text_field :name %><br>
<%= label(:product, :description) %><br>
<%= p.text_area :description %><br>
<%= label(:product, :image) %><br>
<%= p.text_field :image %><br>
<%= label(:product, :quantity) %><br>
<%= p.number_field :quantity, min: 0 %><br>
<%= label(:product, :price) %><br>
<%= p.number_field :price, min: 0 %><br>
<%= p.submit "Edit Product" %> <%end%> 

<%= link_to 'Back', "/" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<h2><%= @product.name %></h2>


<img width="64" height="380" src=<%= @product.image %>
<br>
<p><%= @product.description %><p>
<p>Price: <b><%=@product.price%> </b> </p>
 

<% if is_admin? %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>
<%= link_to 'Back', category_products_path(@product.category_id) %> <br>
<%= link_to 'Destroy Product', "/products/"+@product.id.to_s, method: "delete" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Add new user</h1>

<%= form_for(@user) do |u| %>
<%= u.text_field :first_name, :placeholder => "First Name" %><br>
<%= u.text_field :last_name, :placeholder => "Last Name" %><br>
<%= u.email_field :email, :placeholder => "Email" %><br>
<%= u.password_field :password, :placeholder => "Password" %><br>
<%= u.submit "Create User" %>
<%end%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>